# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 322d6689c32597813a16c58e8932ab38e82be75c74e4806a165f1bce2acad62eded9221d45d4a29168300d01d04a23c76dba95a265474404d5518b88532cfdaf

test:
  secret_key_base: 4f0c50c6d820b5e26a8b2853eedd3095645bfd75fa8916f93b75026893a8ec215181c1a7288a46bb0651ff2a19f0291040fb3e3992f25b6867ae68ce70f7a064

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
